### ISSUE TITLE
AEM Core Forms Components do not have the same events available as the Foundation Components

### ISSUE THREAD

**Issue by royteeuwen** [adobe/aem-core-forms-components#1029]
### Expected Behaviour
We are investigating on migrating from AEM Foundation Forms Components to AEM Core Forms Components and we expect that we can listen to the same events on the `guideBridge`, namely `guideBridge.on("submitStart")` to take actions before the submit action and `guideBridge.on("validationComplete")` to take correct actions when the validation is complete

### Actual Behaviour
Both events are no longer available in the AEM Core Forms Components

#### AEM Version (mention the exact version in case of cloud SDK)
AEM 6.5.19

#### AEM Forms Version
1.1.32

#### Sample Code that illustrates the problem
```
 guideBridge.connect(function() {
            // It's executed before submit
            guideBridge.on('submitStart', (submitEvent) => {
                 // do things like showing a loading shield
            });

            //check if there are any validation errors
            guideBridge.on('validationComplete', (validationEvent, payload) => {
                if (payload.newText.length > 0) {
                    const error = {
                        errorList: payload.newText,
                    };
                    sendPostMessage('validation-failure', error);
                } else {
                    sendPostMessage('validation-success', validationEvent.type);
                }
            });
        });
```

**Comment by rismehta** [comment]
@royteeuwen Thanks for reporting the issue.

We have made certain [GuideBridge events](https://opensource.adobe.com/aem-core-forms-components) accessible for external applications to interact with in core components. However, not all events are exposed, as we advise against incorporating GuideBridge in core components due to their compatibility with headless use-cases.

The core components offer enhanced flexibility due to their modular design, leveraging a [shared SDK](https://opensource.adobe.com/aem-forms-af-runtime/js-docs/) that is also utilized in headless use-cases. The core component is inherently event-driven, providing a comprehensive set of events that can be accessed by subscribing to the form model, as demonstrated below.

`
const onSubmitStart = (event) => {
     console.log(event.detail.fieldId) 
     // you can also check sample implementation here
https://github.com/adobe/aem-core-forms- components/blob/master/ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/af-commons/v1/datalayer/datalayer.js#L122-L140
 };
 const onValidationComplete = (event) => {
     const x = event.payload[0].id;
      // do something with the invalid field
 };
 const initialGbEvents = (guideBridge) => {
    guideBridge.on("submitStart", onSubmitStart);
    guideBridge.getFormModel().subscribe((action) => {
        if (action.type === 'validationComplete') {
            onValidationComplete(action);
        }
    });
 };
 if(window.guideBridge !== undefined){
         bridge = window.guideBridge;
         initialGbEvents(bridge);
 } else {
      window.addEventListener("bridgeInitializeStart", (event)=>{
          bridge = event.detail.guideBridge;
          initialGbEvents(bridge);
      });
 }
 

`

**Comment by rismehta** [comment]
The APIs exposed in the formModel returned by the getFormModel function are listed under the "methods" section on this page: https://opensource.adobe.com/aem-forms-af-runtime/js-docs/interfaces/FormModel.html.

**Comment by rismehta** [comment]
For example, You can use the following code to submit a form, 

```
guideBridge.getFormModel().dispatch({type: 'submit'})
``` 

For more details on the submit event, please visit: [Submit Event Documentation](https://opensource.adobe.com/aem-forms-af-runtime/js-docs/classes/Submit.html).

**Comment by fran-boop** [comment]
@rismehta Thank you for your previous knowledgeable responses. I am wondering if the example given is one that leverages the shared sdk that you mention. Or is this not a recommended method. I am referring to "against incorporating GuideBridge in core components due to their compatibility with headless use-cases." and specifically this code?
`const onSubmitStart = (event) => {
     console.log(event.detail.fieldId) 
 };
 const onValidationComplete = (event) => {
     const x = event.payload[0].id;
      // do something with the invalid field
 };
 const initialGbEvents = (guideBridge) => {
     guideBridge.getFormModel().subscribe((action) => {
            onSubmitStart(action);
    }, 'submit');
    guideBridge.getFormModel().subscribe((action) => {
            onValidationComplete(action);
    }, 'validationComplete');
 };
 if(window.guideBridge !== undefined){
         bridge = window.guideBridge;
         initialGbEvents(bridge);
 } else {
      window.addEventListener("bridgeInitializeStart", (event)=>{
          bridge = event.detail.guideBridge;
          initialGbEvents(bridge);
      });
 }`

If using guidebridge is not recommended how does one get a list of Validation errors in a proper way?

**Comment by rismehta** [comment]
> . I am referring to "against incorporating GuideBridge in core components due to their compatibility with headless use-cases." and specifically this code?

@fran-boop Apologies for the delayed response. If there are web applications that need to interact with adaptive forms, you can still use the GuideBridge APIs for those use cases, which is why I've shared the samples above.

If your logic is contained within a form, you can reuse it for headless as well. It's recommended to utilize the visual rule editor or custom functions. For instance, within a custom function, you could do the following:

```
globals.form.subscribe((action) => {
            onSubmitStart(action);
    }, 'submit');
    globals.form.subscribe((action) => {
            onValidationComplete(action);
    }, 'validationComplete');
```

<img width="1384" alt="Screenshot 2024-09-27 at 1 24 17 PM" src="https://github.com/user-attachments/assets/01bb1876-8eca-43f6-a18e-5e716fefb801">

**Comment by fran-boop** [comment]
@rismehta Thanks for the response! I think that I understand what you are saying. Since these requests are called from within the framework a headless application would be able to access the guidebridge instance much like it would any custom scripts referenced in this way. Is there a way to access the form model at runtime to better explore some of these classes that are provided? For example on a foundation form I might put a guidebridge.resolveNode(); into the console for a specific field. Then I would be able to see the object that relates to that form field. Also another unrelated question but if someone wanted to register a validator on a custom component from within the component view js how would one do that?

**Comment by fran-boop** [comment]
@rismehta I see that method in the documentation and it seems promising. I was hoping that you would be able to do something similar on the actual component level.

Another question I have about this method is: If you have a pattern defined in the authoring as well, will these two conflict since you are setting the property of valid to true? What if the pattern validation is false?

I guess for me, my main question is how is the validation system designed in the runtime?

I imagined that from within a component that extends from the baseField, you would be able to do something similar (set the component as invalid). For example, on the blur events that are assigned in the constructor of most fields, my thought would be to have a validation there and then set the validation of the model there. I see that those fields are read only but maybe I need a helper method to set that property?

Thank you in advance for any guidance and I would love to catch you for a 30min convo if possible.

**Comment by rismehta** [comment]
> Another question I have about this method is: If you have a pattern defined in the authoring as well, will these two conflict since you are setting the property of valid to true? What if the pattern validation is false?

You would typically do this if the out-of-the-box authoring validation constructs don’t meet your use case. Combining both can lead to conflicts

>For example, on the blur events that are assigned in the constructor of most fields, my thought would be to have a validation there and then set the validation of the model there. 

Yes, that’s also an option. It largely depends on the use case. For instance, if this pattern is consistent across all your forms, it’s better to create a single component, modify its view layer, and handle the logic there.

Generally, form runtime engine offer several hook points, and your choice should be based on the specific use case. If it’s unique to one form, you could use the visual rule editor I mentioned earlier.

However, if it’s a pattern that applies to all forms—where validation needs to trigger on certain events for all fields—you can customize the component’s view layer by creating a custom component. 

> I see that those fields are read only but maybe I need a helper method to set that property?

Could you tell me which fields are read-only? You can dynamically set the field's valid property, as I mentioned earlier, even through the component code.

> I guess for me, my main question is how is the validation system designed in the runtime?

The core library manages all form constraints (you can review them [here](https://experienceleague.adobe.com/docs/experience-manager-headless-adaptive-forms/assets/headless-adaptive-forms-specification.pdf?lang=en)) and triggers validity event based on constraint evaluation. The view layer then responds to these events. Here’s the relevant code: [FormFieldBase.js](https://github.com/adobe/aem-core-forms-components/blob/master/ui.frontend/src/view/FormFieldBase.js#L509-L517).

**Comment by rismehta** [comment]
If you could provide the exact use case, we can share a working sample tailored to it.

**Comment by fran-boop** [comment]
@rismehta That sounds great all I need to see is how from withing something that is extending from FormFieldBase.js you can set the component as invalid :)

**Comment by rismehta** [comment]
> I still feel as though it would make more sense to be able to add constraints directly through the component itself. Anyone could potentially remove that rule.

Agreed, the rule can be removed through authoring. If the use case assumes that authors might remove it, you can implement this logic within the component's view layer, as you previously suggested.

> It feels like a regression back to something I would do in foundation components. I want all of my logic contained in one place and to choose what an author can/cannot configure.

This can still be achieved using core components as well. While the Rule Editor makes such customizations easier, modifying the component itself for this logic feels a bit excessive to me. However, if your goal is to restrict authors, creating a custom component would be a suitable approach.

**Comment by fran-boop** [comment]
How would one set the validation from within the component js?

**Comment by rismehta** [comment]
> How would one set the validation from within the component js?

You can reuse the same code you wrote for v1, but tailor it specifically for the component here. For instance, if you'd like this behavior for the TextInputView, you can implement it at this location: https://github.com/adobe/aem-core-forms-components/blob/master/ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/textinput/v1/textinput/clientlibs/site/js/textinputview.js#L74

```
this_model.valid = false;
this._model.errorMessage = <something>
```

**Comment by fran-boop** [comment]
When doing this._model.valid = customValidationFunction(); it does not allow for the setting of the member of the model?
