### ISSUE TITLE
Translation dictionary not picked up for Form Core Components based on page language

### ISSUE THREAD

**Issue by shravanthprasad** [adobe/aem-core-forms-components#1319]
### User Story
I have created a form and dictionary entries are present for different locale(en,fr,de).
After adding the form on a page with lang fr, the translations are not picked up.
Can you please let me know if I am doing something wrong or this is an issue/any workarounds?

Reference articles used:
https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/forms/adaptive-forms-authoring/authoring-adaptive-forms-core-components/create-an-adaptive-form-on-forms-cs/supporting-new-language-localization-core-components

AEM version 6.5.17
core components version 1.1.27-wcmB004

**Comment by rismehta** [comment]
@shravanthprasad It appears you're using an older version of the forms core component that includes a specific hotfix. There may have been multiple fixes since then. You can refer to the sample test collateral here: https://github.com/adobe/aem-core-forms-components/blob/master/ui.tests/test-module/specs/LocaleTest.spec.js. This test performs the same steps mentioned in the article you referred to and might help you identify any missed steps.

**Comment by nagkulkarnisn** [comment]
Hi @rismehta , Can you confirm if this has been resolved in later core components bundle? 
We're planning to upgrade to SP20 (from SP17 hotfix) with forms core components bundle v1.1.36.

**Comment by rismehta** [comment]
@nagkulkarnisn Yes, you can upgrade to SP20 and use version 1.1.48 as specified in the version requirements here: https://github.com/adobe/aem-core-forms-components/blob/release/650/VERSIONS.md.
