### ISSUE TITLE
Name attribute removed for text component in 1.1.38v-SP20 vs 1.1.27v-SP17

### ISSUE THREAD

**Issue by shravanthprasad** [adobe/aem-core-forms-components#1338]
We have a planned upgrade for SP20 and core components v1.1.38 and we see the name attribute is removed from core forms text component. We had some JS logic on the field based on name attribute.
<img width="1302" alt="v1 1 27" src="https://github.com/user-attachments/assets/722cddf9-139d-42d0-b800-45d86c6c89f0">
<img width="1220" alt="v1 1 38" src="https://github.com/user-attachments/assets/6402362e-f862-412f-ad96-bbb16f3b6f1a">

**Comment by rismehta** [comment]
@shravanthprasad In HTML, the <div> element does not standardly support the name attribute. The name attribute is typically used with form elements such as <input>, <select>, and <textarea>. Since it was incorrectly added before, we have now removed it. Could you please update your existing JavaScript code to accommodate this change? I understand this is a backward incompatible change, but aligning with standards will be beneficial in the long run.

**Comment by shravanthprasad** [comment]
Thanks @rismehta for the quick response
