### ISSUE TITLE
Adding dropdown values on field initialization using custom functions

### ISSUE THREAD

**Issue by shravanthprasad** [adobe/aem-core-forms-components#1344]
We are not able to set dropdown enum and enumNames on field initialization.
ex: http://localhost:4502/content/forms/af/core-components-it/samples/customfunctions/populate-dropdown.html

<img width="1054" alt="image" src="https://github.com/user-attachments/assets/2399cd81-69ee-425b-b29f-040d1f90bd36">

AEM version 6.5.20
Core forms component version 1.1.38

**Comment by rismehta** [comment]
@shravanthprasad  This issue was recently resolved in this commit: https://github.com/adobe/aem-core-forms-components/commit/d4417e518f48c2c1e759cde151da2687c9f7dfb9. Please update to the latest core component version compatible with 6.5.20 as detailed here: https://github.com/adobe/aem-core-forms-components/blob/release/650/VERSIONS.md.

**Comment by rismehta** [comment]
@shravanthprasad Upgrading the core component version for forms should be quick, as core components are generally backward compatible due to the strict versioning approach used.

**Comment by rismehta** [comment]
@shravanthprasad I have created a hotfix addressing the issue mentioned, based on version 1.1.38. You can find the hotfix [here](https://github.com/adobe/aem-core-forms-components/releases/tag/core-forms-components-reactor-1.1.39-enumB004).

Please confirm if this release resolves the use case as expected.
