### ISSUE TITLE
Please format file and commit before running validation - Error

### ISSUE THREAD

**Issue by tonijhanel** [adobe/aem-core-forms-components#497]
### Expected Behaviour
I expect that the project will build properly

### Actual Behaviour
When building the project I get an error when building the AF Core Bundle module.  "aem-core-forms-components-master\bundles\core\src\main\java\com\adobe\cq\forms\core\components\internal\models\v1\aemform\AEMFormImpl.java' has not been previously formatted.  Please format file and commit before running validation! "

### Reproduce Scenario (including but not limited to)
Build the maven project 

#### Steps to Reproduce
Build the maven project 

#### Platform and Version
Windows 10

#### Logs taken while reproducing problem

**Comment by ujjwal5** [comment]
@tonijhanel You can find the code formatting rules in the eclipse-formatter.xml [0] file. The code formatting is automatically checked for each build. To automatically format your code, please run:

`mvn clean install -Pformat-code`

[0]: https://github.com/adobe/aem-core-forms-components/blob/master/bundles/af-core/eclipse-formatter.xml

**Comment by nit23uec** [comment]
I suspect this may be due to a trailing character in end-line on Windows older versions. It works on Windows 11, and on linux/Mac based OS.
Thanks for reporting this. While this does not means that the repo has unformatted code, but some character insertion by Windows at EOL which is getting the format checker to fail. To unblock yourself, you can add `-Dformatter.skip=true` in the mvn command.
